app:
  owl:
    output-ontology-syntax: FUNCTIONAL
  datastore:
    url: file:/home/ubuntu/ontology-data-generator/datastore
    input: input
    output: output
    schema: schema
    configuration: configuration
  generator:
    pdgf:
      home:
        url: file:/home/ubuntu/PDGFEnvironment
      datageneration:
        seed: 123456789L
        rng: PdgfDefaultRandom
        scalefactor: 10
        size: 3
        identifier-field-name: __identifier__
        tables:
          AdministrativeStaff: 30
          Article: 50
          AssistantProfessor: 25
          AssociateProfessor: 20
          Book: 30
          Chair: 15
          ClericalStaff: 20
          College: 100
          ConferencePaper: 260
          Course: 40
          Dean: 20
          Department: 7
          Director: 15
          Employee: 100
          Faculty: 15
          FullProfessor: 25
          GraduateCourse: 30
          GraduateStudent: 300
          Institute: 20
          JournalArticle: 200
          Lecturer: 80
          Manual: 90
          Organization: 1
          Person: 500
          PostDoc: 25
          Professor: 20
          Program: 20
          Publication: 200
          Research: 200
          ResearchAssistant: 60
          ResearchGroup: 15
          Schedule: 20
          Software: 100
          Specification: 30
          Student: 500
          SystemsStaff: 30
          TeachingAssistant: 30
          TechnicalReport: 70
          UndergraduateStudent: 200
          University: 1
          UnofficialPublication: 45
          VisitingProfessor: 15
          Work: 90
        properties:
          birthdate:
            constraints:
              minInclusive: 1970-01-01T00:00:00Z
              maxInclusive: 2000-01-01T00:00:00Z
            precision: DAYS
          foundationYear:
            distribution:
              type: Normal
              mean: 2000
              sd: 15
            constrainsts:
              maxInclusive: 2019
          age:
            distribution:
              type: Normal
              mean: 40
              sd: 15
            constrainsts:
              minExclusive: 0
          weight:
            distribution:
              type: Normal
              mean: 75.0
              sd: 20.0
            precision: 2
          salary:
            distribution:
              type: Normal
              mean: 4800
              sd: 2500
          experience:
            distribution:
              type: Normal
              mean: 5
              sd: 3
        dictionaries:
          - url: file:/home/ubuntu/ontology-data-generator/datastore/dictionary/xsd_language_dict.txt
            supportedDatatypes:
              - RDFS_LITERAL
              - XSD_LANGUAGE
              - RDF_LANG_STRING
            keywords:
              conceptKeywords:
                - language tag
                - lang
              propertyKeywords:
                - prop1
          - url: file:/home/ubuntu/ontology-data-generator/datastore/dictionary/personal_data/first_names.dict
            supportedDatatypes:
              - RDFS_LITERAL
              - XSD_STRING
            keywords:
              conceptKeywords:
                - person
              propertyKeywords:
                - first name
          - url: file:/home/ubuntu/ontology-data-generator/datastore/dictionary/personal_data/last_names.dict
            supportedDatatypes:
              - RDFS_LITERAL
              - XSD_STRING
            keywords:
              conceptKeywords:
                - person
              propertyKeywords:
                - last name
          - url: file:/home/ubuntu/ontology-data-generator/datastore/dictionary/personal_data/email_providers.dict
            supportedDatatypes:
              - RDFS_LITERAL
              - XSD_STRING
            keywords:
              propertyKeywords:
                - email provider
          - url: file:/home/ubuntu/ontology-data-generator/datastore/dictionary/geographical/countries.dict
            supportedDatatypes:
              - RDFS_LITERAL
              - XSD_STRING
            keywords:
              propertyKeywords:
                - country
          - url: file:/home/ubuntu/ontology-data-generator/datastore/dictionary/personal_data/hobbies.dict
            supportedDatatypes:
              - RDFS_LITERAL
              - XSD_STRING
            keywords:
              propertyKeywords:
                - hobby
          - url: file:/home/ubuntu/ontology-data-generator/datastore/dictionary/job/occupations.dict
            supportedDatatypes:
              - RDFS_LITERAL
              - XSD_STRING
            keywords:
              conceptKeywords:
                - occupation
              propertyKeywords:
                - name
          - url: file:/home/ubuntu/ontology-data-generator/datastore/dictionary/job/contract_types.dict
            supportedDatatypes:
              - RDFS_LITERAL
              - XSD_STRING
            keywords:
              propertyKeywords:
                - contract type
          - url: file:/home/ubuntu/ontology-data-generator/datastore/dictionary/job/company_names.dict
            supportedDatatypes:
              - RDFS_LITERAL
              - XSD_STRING
            keywords:
              conceptKeywords:
                - company
              propertyKeywords:
                - name
          - url: file:/home/ubuntu/ontology-data-generator/datastore/dictionary/websites.dict
            supportedDatatypes:
              - RDFS_LITERAL
              - XSD_ANY_URI
            keywords:
              propertyKeywords:
                - website
